// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod io {

extern crate alloc;
#[allow(unused_imports, dead_code)]
pub mod github {

extern crate alloc;
#[allow(unused_imports, dead_code)]
pub mod tritium_launcher {

extern crate alloc;
#[allow(unused_imports, dead_code)]
pub mod kubejs {

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TYPE_KIND: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TYPE_KIND: i8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TYPE_KIND: [TypeKind; 5] = [
  TypeKind::Primitive,
  TypeKind::Class,
  TypeKind::Interface,
  TypeKind::Array,
  TypeKind::Event,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct TypeKind(pub i8);
#[allow(non_upper_case_globals)]
impl TypeKind {
  pub const Primitive: Self = Self(0);
  pub const Class: Self = Self(1);
  pub const Interface: Self = Self(2);
  pub const Array: Self = Self(3);
  pub const Event: Self = Self(4);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Primitive,
    Self::Class,
    Self::Interface,
    Self::Array,
    Self::Event,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Primitive => Some("Primitive"),
      Self::Class => Some("Class"),
      Self::Interface => Some("Interface"),
      Self::Array => Some("Array"),
      Self::Event => Some("Event"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for TypeKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for TypeKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for TypeKind {
    type Output = TypeKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for TypeKind {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for TypeKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for TypeKind {}
pub enum ParameterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Parameter<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Parameter<'a> {
  type Inner = Parameter<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Parameter<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Parameter { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ParameterArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Parameter<'bldr>> {
    let mut builder = ParameterBuilder::new(_fbb);
    if let Some(x) = args.type_ { builder.add_type_(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Parameter::VT_NAME, None)}
  }
  #[inline]
  pub fn type_(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Parameter::VT_TYPE_, None)}
  }
}

impl ::flatbuffers::Verifiable for Parameter<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("type_", Self::VT_TYPE_, false)?
     .finish();
    Ok(())
  }
}
pub struct ParameterArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub type_: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ParameterArgs<'a> {
  #[inline]
  fn default() -> Self {
    ParameterArgs {
      name: None,
      type_: None,
    }
  }
}

pub struct ParameterBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ParameterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Parameter::VT_NAME, name);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Parameter::VT_TYPE_, type_);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ParameterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ParameterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Parameter<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Parameter<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Parameter");
      ds.field("name", &self.name());
      ds.field("type_", &self.type_());
      ds.finish()
  }
}
pub enum ConstructorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Constructor<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Constructor<'a> {
  type Inner = Constructor<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Constructor<'a> {
  pub const VT_PARAMETERS: ::flatbuffers::VOffsetT = 4;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Constructor { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ConstructorArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Constructor<'bldr>> {
    let mut builder = ConstructorBuilder::new(_fbb);
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.parameters { builder.add_parameters(x); }
    builder.finish()
  }


  #[inline]
  pub fn parameters(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Parameter<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Parameter>>>>(Constructor::VT_PARAMETERS, None)}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Constructor::VT_DOCUMENTATION, None)}
  }
}

impl ::flatbuffers::Verifiable for Constructor<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Parameter>>>>("parameters", Self::VT_PARAMETERS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .finish();
    Ok(())
  }
}
pub struct ConstructorArgs<'a> {
    pub parameters: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Parameter<'a>>>>>,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ConstructorArgs<'a> {
  #[inline]
  fn default() -> Self {
    ConstructorArgs {
      parameters: None,
      documentation: None,
    }
  }
}

pub struct ConstructorBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ConstructorBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_parameters(&mut self, parameters: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Parameter<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Constructor::VT_PARAMETERS, parameters);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Constructor::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ConstructorBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ConstructorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Constructor<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Constructor<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Constructor");
      ds.field("parameters", &self.parameters());
      ds.field("documentation", &self.documentation());
      ds.finish()
  }
}
pub enum MethodOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Method<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Method<'a> {
  type Inner = Method<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Method<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_RETURN_TYPE: ::flatbuffers::VOffsetT = 6;
  pub const VT_TYPE_PARAMS: ::flatbuffers::VOffsetT = 8;
  pub const VT_PARAMETERS: ::flatbuffers::VOffsetT = 10;
  pub const VT_IS_STATIC: ::flatbuffers::VOffsetT = 12;
  pub const VT_IS_DEPRECATED: ::flatbuffers::VOffsetT = 14;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Method { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MethodArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Method<'bldr>> {
    let mut builder = MethodBuilder::new(_fbb);
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.parameters { builder.add_parameters(x); }
    if let Some(x) = args.type_params { builder.add_type_params(x); }
    if let Some(x) = args.return_type { builder.add_return_type(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_is_deprecated(args.is_deprecated);
    builder.add_is_static(args.is_static);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Method::VT_NAME, None)}
  }
  #[inline]
  pub fn return_type(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Method::VT_RETURN_TYPE, None)}
  }
  #[inline]
  pub fn type_params(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(Method::VT_TYPE_PARAMS, None)}
  }
  #[inline]
  pub fn parameters(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Parameter<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Parameter>>>>(Method::VT_PARAMETERS, None)}
  }
  #[inline]
  pub fn is_static(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Method::VT_IS_STATIC, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_deprecated(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Method::VT_IS_DEPRECATED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Method::VT_DOCUMENTATION, None)}
  }
}

impl ::flatbuffers::Verifiable for Method<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("return_type", Self::VT_RETURN_TYPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("type_params", Self::VT_TYPE_PARAMS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Parameter>>>>("parameters", Self::VT_PARAMETERS, false)?
     .visit_field::<bool>("is_static", Self::VT_IS_STATIC, false)?
     .visit_field::<bool>("is_deprecated", Self::VT_IS_DEPRECATED, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .finish();
    Ok(())
  }
}
pub struct MethodArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub return_type: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub type_params: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub parameters: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Parameter<'a>>>>>,
    pub is_static: bool,
    pub is_deprecated: bool,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for MethodArgs<'a> {
  #[inline]
  fn default() -> Self {
    MethodArgs {
      name: None,
      return_type: None,
      type_params: None,
      parameters: None,
      is_static: false,
      is_deprecated: false,
      documentation: None,
    }
  }
}

pub struct MethodBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MethodBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Method::VT_NAME, name);
  }
  #[inline]
  pub fn add_return_type(&mut self, return_type: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Method::VT_RETURN_TYPE, return_type);
  }
  #[inline]
  pub fn add_type_params(&mut self, type_params: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Method::VT_TYPE_PARAMS, type_params);
  }
  #[inline]
  pub fn add_parameters(&mut self, parameters: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Parameter<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Method::VT_PARAMETERS, parameters);
  }
  #[inline]
  pub fn add_is_static(&mut self, is_static: bool) {
    self.fbb_.push_slot::<bool>(Method::VT_IS_STATIC, is_static, false);
  }
  #[inline]
  pub fn add_is_deprecated(&mut self, is_deprecated: bool) {
    self.fbb_.push_slot::<bool>(Method::VT_IS_DEPRECATED, is_deprecated, false);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Method::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MethodBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MethodBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Method<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Method<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Method");
      ds.field("name", &self.name());
      ds.field("return_type", &self.return_type());
      ds.field("type_params", &self.type_params());
      ds.field("parameters", &self.parameters());
      ds.field("is_static", &self.is_static());
      ds.field("is_deprecated", &self.is_deprecated());
      ds.field("documentation", &self.documentation());
      ds.finish()
  }
}
pub enum FieldOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Field<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Field<'a> {
  type Inner = Field<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Field<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;
  pub const VT_IS_STATIC: ::flatbuffers::VOffsetT = 8;
  pub const VT_IS_DEPRECATED: ::flatbuffers::VOffsetT = 10;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Field { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FieldArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Field<'bldr>> {
    let mut builder = FieldBuilder::new(_fbb);
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.type_ { builder.add_type_(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_is_deprecated(args.is_deprecated);
    builder.add_is_static(args.is_static);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Field::VT_NAME, None)}
  }
  #[inline]
  pub fn type_(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Field::VT_TYPE_, None)}
  }
  #[inline]
  pub fn is_static(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Field::VT_IS_STATIC, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_deprecated(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Field::VT_IS_DEPRECATED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Field::VT_DOCUMENTATION, None)}
  }
}

impl ::flatbuffers::Verifiable for Field<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("type_", Self::VT_TYPE_, false)?
     .visit_field::<bool>("is_static", Self::VT_IS_STATIC, false)?
     .visit_field::<bool>("is_deprecated", Self::VT_IS_DEPRECATED, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .finish();
    Ok(())
  }
}
pub struct FieldArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub type_: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub is_static: bool,
    pub is_deprecated: bool,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for FieldArgs<'a> {
  #[inline]
  fn default() -> Self {
    FieldArgs {
      name: None,
      type_: None,
      is_static: false,
      is_deprecated: false,
      documentation: None,
    }
  }
}

pub struct FieldBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FieldBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Field::VT_NAME, name);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Field::VT_TYPE_, type_);
  }
  #[inline]
  pub fn add_is_static(&mut self, is_static: bool) {
    self.fbb_.push_slot::<bool>(Field::VT_IS_STATIC, is_static, false);
  }
  #[inline]
  pub fn add_is_deprecated(&mut self, is_deprecated: bool) {
    self.fbb_.push_slot::<bool>(Field::VT_IS_DEPRECATED, is_deprecated, false);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Field::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FieldBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FieldBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Field<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Field<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Field");
      ds.field("name", &self.name());
      ds.field("type_", &self.type_());
      ds.field("is_static", &self.is_static());
      ds.field("is_deprecated", &self.is_deprecated());
      ds.field("documentation", &self.documentation());
      ds.finish()
  }
}
pub enum ClassDefinitionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ClassDefinition<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ClassDefinition<'a> {
  type Inner = ClassDefinition<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ClassDefinition<'a> {
  pub const VT_FULL_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_SIMPLE_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_KIND: ::flatbuffers::VOffsetT = 8;
  pub const VT_TYPE_PARAMS: ::flatbuffers::VOffsetT = 10;
  pub const VT_METHODS: ::flatbuffers::VOffsetT = 12;
  pub const VT_FIELDS: ::flatbuffers::VOffsetT = 14;
  pub const VT_CONSTRUCTORS: ::flatbuffers::VOffsetT = 16;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 18;
  pub const VT_SUPER_CLASS: ::flatbuffers::VOffsetT = 20;
  pub const VT_INTERFACES: ::flatbuffers::VOffsetT = 22;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ClassDefinition { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ClassDefinitionArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ClassDefinition<'bldr>> {
    let mut builder = ClassDefinitionBuilder::new(_fbb);
    if let Some(x) = args.interfaces { builder.add_interfaces(x); }
    if let Some(x) = args.super_class { builder.add_super_class(x); }
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.constructors { builder.add_constructors(x); }
    if let Some(x) = args.fields { builder.add_fields(x); }
    if let Some(x) = args.methods { builder.add_methods(x); }
    if let Some(x) = args.type_params { builder.add_type_params(x); }
    if let Some(x) = args.simple_name { builder.add_simple_name(x); }
    if let Some(x) = args.full_name { builder.add_full_name(x); }
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn full_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ClassDefinition::VT_FULL_NAME, None)}
  }
  #[inline]
  pub fn simple_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ClassDefinition::VT_SIMPLE_NAME, None)}
  }
  #[inline]
  pub fn kind(&self) -> TypeKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TypeKind>(ClassDefinition::VT_KIND, Some(TypeKind::Class)).unwrap()}
  }
  #[inline]
  pub fn type_params(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(ClassDefinition::VT_TYPE_PARAMS, None)}
  }
  #[inline]
  pub fn methods(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Method<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Method>>>>(ClassDefinition::VT_METHODS, None)}
  }
  #[inline]
  pub fn fields(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Field<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Field>>>>(ClassDefinition::VT_FIELDS, None)}
  }
  #[inline]
  pub fn constructors(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Constructor<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Constructor>>>>(ClassDefinition::VT_CONSTRUCTORS, None)}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ClassDefinition::VT_DOCUMENTATION, None)}
  }
  #[inline]
  pub fn super_class(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ClassDefinition::VT_SUPER_CLASS, None)}
  }
  #[inline]
  pub fn interfaces(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(ClassDefinition::VT_INTERFACES, None)}
  }
}

impl ::flatbuffers::Verifiable for ClassDefinition<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("full_name", Self::VT_FULL_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("simple_name", Self::VT_SIMPLE_NAME, false)?
     .visit_field::<TypeKind>("kind", Self::VT_KIND, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("type_params", Self::VT_TYPE_PARAMS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Method>>>>("methods", Self::VT_METHODS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Field>>>>("fields", Self::VT_FIELDS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Constructor>>>>("constructors", Self::VT_CONSTRUCTORS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("super_class", Self::VT_SUPER_CLASS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("interfaces", Self::VT_INTERFACES, false)?
     .finish();
    Ok(())
  }
}
pub struct ClassDefinitionArgs<'a> {
    pub full_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub simple_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub kind: TypeKind,
    pub type_params: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub methods: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Method<'a>>>>>,
    pub fields: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Field<'a>>>>>,
    pub constructors: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Constructor<'a>>>>>,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub super_class: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub interfaces: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for ClassDefinitionArgs<'a> {
  #[inline]
  fn default() -> Self {
    ClassDefinitionArgs {
      full_name: None,
      simple_name: None,
      kind: TypeKind::Class,
      type_params: None,
      methods: None,
      fields: None,
      constructors: None,
      documentation: None,
      super_class: None,
      interfaces: None,
    }
  }
}

pub struct ClassDefinitionBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ClassDefinitionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_full_name(&mut self, full_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_FULL_NAME, full_name);
  }
  #[inline]
  pub fn add_simple_name(&mut self, simple_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_SIMPLE_NAME, simple_name);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: TypeKind) {
    self.fbb_.push_slot::<TypeKind>(ClassDefinition::VT_KIND, kind, TypeKind::Class);
  }
  #[inline]
  pub fn add_type_params(&mut self, type_params: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_TYPE_PARAMS, type_params);
  }
  #[inline]
  pub fn add_methods(&mut self, methods: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Method<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_METHODS, methods);
  }
  #[inline]
  pub fn add_fields(&mut self, fields: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Field<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_FIELDS, fields);
  }
  #[inline]
  pub fn add_constructors(&mut self, constructors: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Constructor<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_CONSTRUCTORS, constructors);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn add_super_class(&mut self, super_class: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_SUPER_CLASS, super_class);
  }
  #[inline]
  pub fn add_interfaces(&mut self, interfaces: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClassDefinition::VT_INTERFACES, interfaces);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ClassDefinitionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ClassDefinitionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ClassDefinition<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ClassDefinition<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ClassDefinition");
      ds.field("full_name", &self.full_name());
      ds.field("simple_name", &self.simple_name());
      ds.field("kind", &self.kind());
      ds.field("type_params", &self.type_params());
      ds.field("methods", &self.methods());
      ds.field("fields", &self.fields());
      ds.field("constructors", &self.constructors());
      ds.field("documentation", &self.documentation());
      ds.field("super_class", &self.super_class());
      ds.field("interfaces", &self.interfaces());
      ds.finish()
  }
}
pub enum BindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Binding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Binding<'a> {
  type Inner = Binding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Binding<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 8;
  pub const VT_SIDE: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Binding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Binding<'bldr>> {
    let mut builder = BindingBuilder::new(_fbb);
    if let Some(x) = args.side { builder.add_side(x); }
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.type_ { builder.add_type_(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Binding::VT_NAME, None)}
  }
  #[inline]
  pub fn type_(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Binding::VT_TYPE_, None)}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Binding::VT_DOCUMENTATION, None)}
  }
  #[inline]
  pub fn side(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Binding::VT_SIDE, None)}
  }
}

impl ::flatbuffers::Verifiable for Binding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("type_", Self::VT_TYPE_, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("side", Self::VT_SIDE, false)?
     .finish();
    Ok(())
  }
}
pub struct BindingArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub type_: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub side: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for BindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    BindingArgs {
      name: None,
      type_: None,
      documentation: None,
      side: None,
    }
  }
}

pub struct BindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Binding::VT_NAME, name);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Binding::VT_TYPE_, type_);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Binding::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn add_side(&mut self, side: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Binding::VT_SIDE, side);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Binding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Binding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Binding");
      ds.field("name", &self.name());
      ds.field("type_", &self.type_());
      ds.field("documentation", &self.documentation());
      ds.field("side", &self.side());
      ds.finish()
  }
}
pub enum RecipeKeyInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RecipeKeyInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RecipeKeyInfo<'a> {
  type Inner = RecipeKeyInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RecipeKeyInfo<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;
  pub const VT_OPTIONAL: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RecipeKeyInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RecipeKeyInfoArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RecipeKeyInfo<'bldr>> {
    let mut builder = RecipeKeyInfoBuilder::new(_fbb);
    if let Some(x) = args.type_ { builder.add_type_(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_optional(args.optional);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RecipeKeyInfo::VT_NAME, None)}
  }
  #[inline]
  pub fn type_(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RecipeKeyInfo::VT_TYPE_, None)}
  }
  #[inline]
  pub fn optional(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(RecipeKeyInfo::VT_OPTIONAL, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RecipeKeyInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("type_", Self::VT_TYPE_, false)?
     .visit_field::<bool>("optional", Self::VT_OPTIONAL, false)?
     .finish();
    Ok(())
  }
}
pub struct RecipeKeyInfoArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub type_: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub optional: bool,
}
impl<'a> Default for RecipeKeyInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    RecipeKeyInfoArgs {
      name: None,
      type_: None,
      optional: false,
    }
  }
}

pub struct RecipeKeyInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RecipeKeyInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeKeyInfo::VT_NAME, name);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeKeyInfo::VT_TYPE_, type_);
  }
  #[inline]
  pub fn add_optional(&mut self, optional: bool) {
    self.fbb_.push_slot::<bool>(RecipeKeyInfo::VT_OPTIONAL, optional, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RecipeKeyInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RecipeKeyInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RecipeKeyInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RecipeKeyInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RecipeKeyInfo");
      ds.field("name", &self.name());
      ds.field("type_", &self.type_());
      ds.field("optional", &self.optional());
      ds.finish()
  }
}
pub enum RecipeSchemaBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RecipeSchemaBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RecipeSchemaBinding<'a> {
  type Inner = RecipeSchemaBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RecipeSchemaBinding<'a> {
  pub const VT_NAMESPACE: ::flatbuffers::VOffsetT = 4;
  pub const VT_SCHEMA_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_RECIPE_CLASS: ::flatbuffers::VOffsetT = 8;
  pub const VT_KEYS: ::flatbuffers::VOffsetT = 10;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RecipeSchemaBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RecipeSchemaBindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RecipeSchemaBinding<'bldr>> {
    let mut builder = RecipeSchemaBindingBuilder::new(_fbb);
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.keys { builder.add_keys(x); }
    if let Some(x) = args.recipe_class { builder.add_recipe_class(x); }
    if let Some(x) = args.schema_id { builder.add_schema_id(x); }
    if let Some(x) = args.namespace { builder.add_namespace(x); }
    builder.finish()
  }


  #[inline]
  pub fn namespace(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RecipeSchemaBinding::VT_NAMESPACE, None)}
  }
  #[inline]
  pub fn schema_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RecipeSchemaBinding::VT_SCHEMA_ID, None)}
  }
  #[inline]
  pub fn recipe_class(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RecipeSchemaBinding::VT_RECIPE_CLASS, None)}
  }
  #[inline]
  pub fn keys(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<RecipeKeyInfo<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<RecipeKeyInfo>>>>(RecipeSchemaBinding::VT_KEYS, None)}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(RecipeSchemaBinding::VT_DOCUMENTATION, None)}
  }
}

impl ::flatbuffers::Verifiable for RecipeSchemaBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("namespace", Self::VT_NAMESPACE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("schema_id", Self::VT_SCHEMA_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("recipe_class", Self::VT_RECIPE_CLASS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<RecipeKeyInfo>>>>("keys", Self::VT_KEYS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .finish();
    Ok(())
  }
}
pub struct RecipeSchemaBindingArgs<'a> {
    pub namespace: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub schema_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub recipe_class: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub keys: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<RecipeKeyInfo<'a>>>>>,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for RecipeSchemaBindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    RecipeSchemaBindingArgs {
      namespace: None,
      schema_id: None,
      recipe_class: None,
      keys: None,
      documentation: None,
    }
  }
}

pub struct RecipeSchemaBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RecipeSchemaBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_namespace(&mut self, namespace: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeSchemaBinding::VT_NAMESPACE, namespace);
  }
  #[inline]
  pub fn add_schema_id(&mut self, schema_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeSchemaBinding::VT_SCHEMA_ID, schema_id);
  }
  #[inline]
  pub fn add_recipe_class(&mut self, recipe_class: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeSchemaBinding::VT_RECIPE_CLASS, recipe_class);
  }
  #[inline]
  pub fn add_keys(&mut self, keys: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<RecipeKeyInfo<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeSchemaBinding::VT_KEYS, keys);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RecipeSchemaBinding::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RecipeSchemaBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RecipeSchemaBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RecipeSchemaBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RecipeSchemaBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RecipeSchemaBinding");
      ds.field("namespace", &self.namespace());
      ds.field("schema_id", &self.schema_id());
      ds.field("recipe_class", &self.recipe_class());
      ds.field("keys", &self.keys());
      ds.field("documentation", &self.documentation());
      ds.finish()
  }
}
pub enum EventBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EventBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EventBinding<'a> {
  type Inner = EventBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EventBinding<'a> {
  pub const VT_GROUP_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_EVENT_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_EVENT_CLASS: ::flatbuffers::VOffsetT = 8;
  pub const VT_SIDE: ::flatbuffers::VOffsetT = 10;
  pub const VT_EXTRA_TYPE: ::flatbuffers::VOffsetT = 12;
  pub const VT_TARGET_REQUIRED: ::flatbuffers::VOffsetT = 14;
  pub const VT_DOCUMENTATION: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EventBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EventBindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EventBinding<'bldr>> {
    let mut builder = EventBindingBuilder::new(_fbb);
    if let Some(x) = args.documentation { builder.add_documentation(x); }
    if let Some(x) = args.extra_type { builder.add_extra_type(x); }
    if let Some(x) = args.side { builder.add_side(x); }
    if let Some(x) = args.event_class { builder.add_event_class(x); }
    if let Some(x) = args.event_name { builder.add_event_name(x); }
    if let Some(x) = args.group_name { builder.add_group_name(x); }
    builder.add_target_required(args.target_required);
    builder.finish()
  }


  #[inline]
  pub fn group_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventBinding::VT_GROUP_NAME, None)}
  }
  #[inline]
  pub fn event_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventBinding::VT_EVENT_NAME, None)}
  }
  #[inline]
  pub fn event_class(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventBinding::VT_EVENT_CLASS, None)}
  }
  #[inline]
  pub fn side(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventBinding::VT_SIDE, None)}
  }
  #[inline]
  pub fn extra_type(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventBinding::VT_EXTRA_TYPE, None)}
  }
  #[inline]
  pub fn target_required(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(EventBinding::VT_TARGET_REQUIRED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn documentation(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventBinding::VT_DOCUMENTATION, None)}
  }
}

impl ::flatbuffers::Verifiable for EventBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("group_name", Self::VT_GROUP_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("event_name", Self::VT_EVENT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("event_class", Self::VT_EVENT_CLASS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("side", Self::VT_SIDE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("extra_type", Self::VT_EXTRA_TYPE, false)?
     .visit_field::<bool>("target_required", Self::VT_TARGET_REQUIRED, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("documentation", Self::VT_DOCUMENTATION, false)?
     .finish();
    Ok(())
  }
}
pub struct EventBindingArgs<'a> {
    pub group_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub event_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub event_class: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub side: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub extra_type: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub target_required: bool,
    pub documentation: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EventBindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    EventBindingArgs {
      group_name: None,
      event_name: None,
      event_class: None,
      side: None,
      extra_type: None,
      target_required: false,
      documentation: None,
    }
  }
}

pub struct EventBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EventBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_group_name(&mut self, group_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBinding::VT_GROUP_NAME, group_name);
  }
  #[inline]
  pub fn add_event_name(&mut self, event_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBinding::VT_EVENT_NAME, event_name);
  }
  #[inline]
  pub fn add_event_class(&mut self, event_class: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBinding::VT_EVENT_CLASS, event_class);
  }
  #[inline]
  pub fn add_side(&mut self, side: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBinding::VT_SIDE, side);
  }
  #[inline]
  pub fn add_extra_type(&mut self, extra_type: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBinding::VT_EXTRA_TYPE, extra_type);
  }
  #[inline]
  pub fn add_target_required(&mut self, target_required: bool) {
    self.fbb_.push_slot::<bool>(EventBinding::VT_TARGET_REQUIRED, target_required, false);
  }
  #[inline]
  pub fn add_documentation(&mut self, documentation: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBinding::VT_DOCUMENTATION, documentation);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EventBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EventBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EventBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EventBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EventBinding");
      ds.field("group_name", &self.group_name());
      ds.field("event_name", &self.event_name());
      ds.field("event_class", &self.event_class());
      ds.field("side", &self.side());
      ds.field("extra_type", &self.extra_type());
      ds.field("target_required", &self.target_required());
      ds.field("documentation", &self.documentation());
      ds.finish()
  }
}
pub enum KubeTypingsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KubeTypings<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for KubeTypings<'a> {
  type Inner = KubeTypings<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> KubeTypings<'a> {
  pub const VT_MINECRAFT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_LOADER: ::flatbuffers::VOffsetT = 6;
  pub const VT_CLASSES: ::flatbuffers::VOffsetT = 8;
  pub const VT_BINDINGS: ::flatbuffers::VOffsetT = 10;
  pub const VT_EVENTS: ::flatbuffers::VOffsetT = 12;
  pub const VT_RECIPES: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    KubeTypings { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KubeTypingsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<KubeTypings<'bldr>> {
    let mut builder = KubeTypingsBuilder::new(_fbb);
    if let Some(x) = args.recipes { builder.add_recipes(x); }
    if let Some(x) = args.events { builder.add_events(x); }
    if let Some(x) = args.bindings { builder.add_bindings(x); }
    if let Some(x) = args.classes { builder.add_classes(x); }
    if let Some(x) = args.loader { builder.add_loader(x); }
    if let Some(x) = args.minecraft_version { builder.add_minecraft_version(x); }
    builder.finish()
  }


  #[inline]
  pub fn minecraft_version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(KubeTypings::VT_MINECRAFT_VERSION, None)}
  }
  #[inline]
  pub fn loader(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(KubeTypings::VT_LOADER, None)}
  }
  #[inline]
  pub fn classes(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ClassDefinition<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ClassDefinition>>>>(KubeTypings::VT_CLASSES, None)}
  }
  #[inline]
  pub fn bindings(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Binding<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Binding>>>>(KubeTypings::VT_BINDINGS, None)}
  }
  #[inline]
  pub fn events(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EventBinding<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EventBinding>>>>(KubeTypings::VT_EVENTS, None)}
  }
  #[inline]
  pub fn recipes(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<RecipeSchemaBinding<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<RecipeSchemaBinding>>>>(KubeTypings::VT_RECIPES, None)}
  }
}

impl ::flatbuffers::Verifiable for KubeTypings<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("minecraft_version", Self::VT_MINECRAFT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("loader", Self::VT_LOADER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ClassDefinition>>>>("classes", Self::VT_CLASSES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Binding>>>>("bindings", Self::VT_BINDINGS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<EventBinding>>>>("events", Self::VT_EVENTS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<RecipeSchemaBinding>>>>("recipes", Self::VT_RECIPES, false)?
     .finish();
    Ok(())
  }
}
pub struct KubeTypingsArgs<'a> {
    pub minecraft_version: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub loader: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub classes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ClassDefinition<'a>>>>>,
    pub bindings: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Binding<'a>>>>>,
    pub events: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EventBinding<'a>>>>>,
    pub recipes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<RecipeSchemaBinding<'a>>>>>,
}
impl<'a> Default for KubeTypingsArgs<'a> {
  #[inline]
  fn default() -> Self {
    KubeTypingsArgs {
      minecraft_version: None,
      loader: None,
      classes: None,
      bindings: None,
      events: None,
      recipes: None,
    }
  }
}

pub struct KubeTypingsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> KubeTypingsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_minecraft_version(&mut self, minecraft_version: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KubeTypings::VT_MINECRAFT_VERSION, minecraft_version);
  }
  #[inline]
  pub fn add_loader(&mut self, loader: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KubeTypings::VT_LOADER, loader);
  }
  #[inline]
  pub fn add_classes(&mut self, classes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ClassDefinition<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KubeTypings::VT_CLASSES, classes);
  }
  #[inline]
  pub fn add_bindings(&mut self, bindings: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Binding<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KubeTypings::VT_BINDINGS, bindings);
  }
  #[inline]
  pub fn add_events(&mut self, events: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<EventBinding<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KubeTypings::VT_EVENTS, events);
  }
  #[inline]
  pub fn add_recipes(&mut self, recipes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<RecipeSchemaBinding<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KubeTypings::VT_RECIPES, recipes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> KubeTypingsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KubeTypingsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<KubeTypings<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for KubeTypings<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("KubeTypings");
      ds.field("minecraft_version", &self.minecraft_version());
      ds.field("loader", &self.loader());
      ds.field("classes", &self.classes());
      ds.field("bindings", &self.bindings());
      ds.field("events", &self.events());
      ds.field("recipes", &self.recipes());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `KubeTypings`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_kube_typings_unchecked`.
pub fn root_as_kube_typings(buf: &[u8]) -> Result<KubeTypings<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<KubeTypings>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `KubeTypings` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_kube_typings_unchecked`.
pub fn size_prefixed_root_as_kube_typings(buf: &[u8]) -> Result<KubeTypings<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<KubeTypings>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `KubeTypings` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_kube_typings_unchecked`.
pub fn root_as_kube_typings_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<KubeTypings<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<KubeTypings<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `KubeTypings` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_kube_typings_unchecked`.
pub fn size_prefixed_root_as_kube_typings_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<KubeTypings<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<KubeTypings<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a KubeTypings and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `KubeTypings`.
pub unsafe fn root_as_kube_typings_unchecked(buf: &[u8]) -> KubeTypings<'_> {
  unsafe { ::flatbuffers::root_unchecked::<KubeTypings>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed KubeTypings and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `KubeTypings`.
pub unsafe fn size_prefixed_root_as_kube_typings_unchecked(buf: &[u8]) -> KubeTypings<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<KubeTypings>(buf) }
}
#[inline]
pub fn finish_kube_typings_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<KubeTypings<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_kube_typings_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<KubeTypings<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod kubejs
}  // pub mod tritium_launcher
}  // pub mod github
}  // pub mod io

