// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Binding extends com.google.flatbuffers.Table {
  public static Binding getRootAsBinding(ByteBuffer _bb) { return getRootAsBinding(_bb, new Binding()); }
  public static Binding getRootAsBinding(ByteBuffer _bb, Binding obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Binding __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String type() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String documentation() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer documentationAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer documentationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String side() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sideAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer sideInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createBinding(FlatBufferBuilder builder,
      int nameOffset,
      int typeOffset,
      int documentationOffset,
      int sideOffset) {
    builder.startTable(4);
    Binding.addSide(builder, sideOffset);
    Binding.addDocumentation(builder, documentationOffset);
    Binding.addType(builder, typeOffset);
    Binding.addName(builder, nameOffset);
    return Binding.endBinding(builder);
  }

  public static void startBinding(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(1, typeOffset, 0); }
  public static void addDocumentation(FlatBufferBuilder builder, int documentationOffset) { builder.addOffset(2, documentationOffset, 0); }
  public static void addSide(FlatBufferBuilder builder, int sideOffset) { builder.addOffset(3, sideOffset, 0); }
  public static int endBinding(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Binding get(int j) { return get(new Binding(), j); }
    public Binding get(Binding obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

