// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.StringVector;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ClassDefinition extends com.google.flatbuffers.Table {
  public static ClassDefinition getRootAsClassDefinition(ByteBuffer _bb) { return getRootAsClassDefinition(_bb, new ClassDefinition()); }
  public static ClassDefinition getRootAsClassDefinition(ByteBuffer _bb, ClassDefinition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ClassDefinition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String fullName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fullNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer fullNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String simpleName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer simpleNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer simpleNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public byte kind() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 1; }
  public String typeParams(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int typeParamsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector typeParamsVector() { return typeParamsVector(new StringVector()); }
  public StringVector typeParamsVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Method methods(int j) { return methods(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Method(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Method methods(io.github.tritium_launcher.launcher.extension.kubejs.typings.Method obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int methodsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Method.Vector methodsVector() { return methodsVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Method.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Method.Vector methodsVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.Method.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Field fields(int j) { return fields(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Field(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Field fields(io.github.tritium_launcher.launcher.extension.kubejs.typings.Field obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int fieldsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Field.Vector fieldsVector() { return fieldsVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Field.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Field.Vector fieldsVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.Field.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor constructors(int j) { return constructors(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor constructors(io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor obj, int j) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int constructorsLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor.Vector constructorsVector() { return constructorsVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor.Vector constructorsVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.Constructor.Vector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String documentation() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer documentationAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer documentationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public String superClass() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer superClassAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer superClassInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String interfaces(int j) { int o = __offset(22); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int interfacesLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public StringVector interfacesVector() { return interfacesVector(new StringVector()); }
  public StringVector interfacesVector(StringVector obj) { int o = __offset(22); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createClassDefinition(FlatBufferBuilder builder,
      int fullNameOffset,
      int simpleNameOffset,
      byte kind,
      int typeParamsOffset,
      int methodsOffset,
      int fieldsOffset,
      int constructorsOffset,
      int documentationOffset,
      int superClassOffset,
      int interfacesOffset) {
    builder.startTable(10);
    ClassDefinition.addInterfaces(builder, interfacesOffset);
    ClassDefinition.addSuperClass(builder, superClassOffset);
    ClassDefinition.addDocumentation(builder, documentationOffset);
    ClassDefinition.addConstructors(builder, constructorsOffset);
    ClassDefinition.addFields(builder, fieldsOffset);
    ClassDefinition.addMethods(builder, methodsOffset);
    ClassDefinition.addTypeParams(builder, typeParamsOffset);
    ClassDefinition.addSimpleName(builder, simpleNameOffset);
    ClassDefinition.addFullName(builder, fullNameOffset);
    ClassDefinition.addKind(builder, kind);
    return ClassDefinition.endClassDefinition(builder);
  }

  public static void startClassDefinition(FlatBufferBuilder builder) { builder.startTable(10); }
  public static void addFullName(FlatBufferBuilder builder, int fullNameOffset) { builder.addOffset(0, fullNameOffset, 0); }
  public static void addSimpleName(FlatBufferBuilder builder, int simpleNameOffset) { builder.addOffset(1, simpleNameOffset, 0); }
  public static void addKind(FlatBufferBuilder builder, byte kind) { builder.addByte(2, kind, 1); }
  public static void addTypeParams(FlatBufferBuilder builder, int typeParamsOffset) { builder.addOffset(3, typeParamsOffset, 0); }
  public static int createTypeParamsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTypeParamsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMethods(FlatBufferBuilder builder, int methodsOffset) { builder.addOffset(4, methodsOffset, 0); }
  public static int createMethodsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMethodsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addFields(FlatBufferBuilder builder, int fieldsOffset) { builder.addOffset(5, fieldsOffset, 0); }
  public static int createFieldsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFieldsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addConstructors(FlatBufferBuilder builder, int constructorsOffset) { builder.addOffset(6, constructorsOffset, 0); }
  public static int createConstructorsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startConstructorsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDocumentation(FlatBufferBuilder builder, int documentationOffset) { builder.addOffset(7, documentationOffset, 0); }
  public static void addSuperClass(FlatBufferBuilder builder, int superClassOffset) { builder.addOffset(8, superClassOffset, 0); }
  public static void addInterfaces(FlatBufferBuilder builder, int interfacesOffset) { builder.addOffset(9, interfacesOffset, 0); }
  public static int createInterfacesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInterfacesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endClassDefinition(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ClassDefinition get(int j) { return get(new ClassDefinition(), j); }
    public ClassDefinition get(ClassDefinition obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

