// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Constructor extends com.google.flatbuffers.Table {
  public static Constructor getRootAsConstructor(ByteBuffer _bb) { return getRootAsConstructor(_bb, new Constructor()); }
  public static Constructor getRootAsConstructor(ByteBuffer _bb, Constructor obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Constructor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter parameters(int j) { return parameters(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter parameters(io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parametersLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector parametersVector() { return parametersVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector parametersVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String documentation() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer documentationAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer documentationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createConstructor(FlatBufferBuilder builder,
      int parametersOffset,
      int documentationOffset) {
    builder.startTable(2);
    Constructor.addDocumentation(builder, documentationOffset);
    Constructor.addParameters(builder, parametersOffset);
    return Constructor.endConstructor(builder);
  }

  public static void startConstructor(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addParameters(FlatBufferBuilder builder, int parametersOffset) { builder.addOffset(0, parametersOffset, 0); }
  public static int createParametersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParametersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDocumentation(FlatBufferBuilder builder, int documentationOffset) { builder.addOffset(1, documentationOffset, 0); }
  public static int endConstructor(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Constructor get(int j) { return get(new Constructor(), j); }
    public Constructor get(Constructor obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

