// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EventBinding extends com.google.flatbuffers.Table {
  public static EventBinding getRootAsEventBinding(ByteBuffer _bb) { return getRootAsEventBinding(_bb, new EventBinding()); }
  public static EventBinding getRootAsEventBinding(ByteBuffer _bb, EventBinding obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EventBinding __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String groupName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer groupNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer groupNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String eventName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer eventNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String eventClass() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventClassAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer eventClassInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String side() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sideAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer sideInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String extraType() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer extraTypeAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer extraTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public boolean targetRequired() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String documentation() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer documentationAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer documentationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }

  public static int createEventBinding(FlatBufferBuilder builder,
      int groupNameOffset,
      int eventNameOffset,
      int eventClassOffset,
      int sideOffset,
      int extraTypeOffset,
      boolean targetRequired,
      int documentationOffset) {
    builder.startTable(7);
    EventBinding.addDocumentation(builder, documentationOffset);
    EventBinding.addExtraType(builder, extraTypeOffset);
    EventBinding.addSide(builder, sideOffset);
    EventBinding.addEventClass(builder, eventClassOffset);
    EventBinding.addEventName(builder, eventNameOffset);
    EventBinding.addGroupName(builder, groupNameOffset);
    EventBinding.addTargetRequired(builder, targetRequired);
    return EventBinding.endEventBinding(builder);
  }

  public static void startEventBinding(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addGroupName(FlatBufferBuilder builder, int groupNameOffset) { builder.addOffset(0, groupNameOffset, 0); }
  public static void addEventName(FlatBufferBuilder builder, int eventNameOffset) { builder.addOffset(1, eventNameOffset, 0); }
  public static void addEventClass(FlatBufferBuilder builder, int eventClassOffset) { builder.addOffset(2, eventClassOffset, 0); }
  public static void addSide(FlatBufferBuilder builder, int sideOffset) { builder.addOffset(3, sideOffset, 0); }
  public static void addExtraType(FlatBufferBuilder builder, int extraTypeOffset) { builder.addOffset(4, extraTypeOffset, 0); }
  public static void addTargetRequired(FlatBufferBuilder builder, boolean targetRequired) { builder.addBoolean(5, targetRequired, false); }
  public static void addDocumentation(FlatBufferBuilder builder, int documentationOffset) { builder.addOffset(6, documentationOffset, 0); }
  public static int endEventBinding(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EventBinding get(int j) { return get(new EventBinding(), j); }
    public EventBinding get(EventBinding obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

