/*
 * Copyright (c) 2025 FooterMan and contributors.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class KubeTypings extends com.google.flatbuffers.Table {
  public static KubeTypings getRootAsKubeTypings(ByteBuffer _bb) { return getRootAsKubeTypings(_bb, new KubeTypings()); }
  public static KubeTypings getRootAsKubeTypings(ByteBuffer _bb, KubeTypings obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KubeTypings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String minecraftVersion() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer minecraftVersionAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer minecraftVersionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String loader() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer loaderAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer loaderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition classes(int j) { return classes(new io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition classes(io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int classesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition.Vector classesVector() { return classesVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition.Vector classesVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.ClassDefinition.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding bindings(int j) { return bindings(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding bindings(io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int bindingsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding.Vector bindingsVector() { return bindingsVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding.Vector bindingsVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.Binding.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding events(int j) { return events(new io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding events(io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int eventsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding.Vector eventsVector() { return eventsVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding.Vector eventsVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.EventBinding.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding recipes(int j) { return recipes(new io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding recipes(io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int recipesLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding.Vector recipesVector() { return recipesVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding.Vector recipesVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeSchemaBinding.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createKubeTypings(FlatBufferBuilder builder,
      int minecraftVersionOffset,
      int loaderOffset,
      int classesOffset,
      int bindingsOffset,
      int eventsOffset,
      int recipesOffset) {
    builder.startTable(6);
    KubeTypings.addRecipes(builder, recipesOffset);
    KubeTypings.addEvents(builder, eventsOffset);
    KubeTypings.addBindings(builder, bindingsOffset);
    KubeTypings.addClasses(builder, classesOffset);
    KubeTypings.addLoader(builder, loaderOffset);
    KubeTypings.addMinecraftVersion(builder, minecraftVersionOffset);
    return KubeTypings.endKubeTypings(builder);
  }

  public static void startKubeTypings(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addMinecraftVersion(FlatBufferBuilder builder, int minecraftVersionOffset) { builder.addOffset(0, minecraftVersionOffset, 0); }
  public static void addLoader(FlatBufferBuilder builder, int loaderOffset) { builder.addOffset(1, loaderOffset, 0); }
  public static void addClasses(FlatBufferBuilder builder, int classesOffset) { builder.addOffset(2, classesOffset, 0); }
  public static int createClassesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startClassesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addBindings(FlatBufferBuilder builder, int bindingsOffset) { builder.addOffset(3, bindingsOffset, 0); }
  public static int createBindingsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBindingsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEvents(FlatBufferBuilder builder, int eventsOffset) { builder.addOffset(4, eventsOffset, 0); }
  public static int createEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRecipes(FlatBufferBuilder builder, int recipesOffset) { builder.addOffset(5, recipesOffset, 0); }
  public static int createRecipesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRecipesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endKubeTypings(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishKubeTypingsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedKubeTypingsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KubeTypings get(int j) { return get(new KubeTypings(), j); }
    public KubeTypings get(KubeTypings obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

