// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.StringVector;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Method extends com.google.flatbuffers.Table {
  public static Method getRootAsMethod(ByteBuffer _bb) { return getRootAsMethod(_bb, new Method()); }
  public static Method getRootAsMethod(ByteBuffer _bb, Method obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Method __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String returnType() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer returnTypeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer returnTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String typeParams(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int typeParamsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public StringVector typeParamsVector() { return typeParamsVector(new StringVector()); }
  public StringVector typeParamsVector(StringVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter parameters(int j) { return parameters(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter parameters(io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int parametersLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector parametersVector() { return parametersVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector parametersVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.Parameter.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean isStatic() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean isDeprecated() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String documentation() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer documentationAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer documentationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }

  public static int createMethod(FlatBufferBuilder builder,
      int nameOffset,
      int returnTypeOffset,
      int typeParamsOffset,
      int parametersOffset,
      boolean isStatic,
      boolean isDeprecated,
      int documentationOffset) {
    builder.startTable(7);
    Method.addDocumentation(builder, documentationOffset);
    Method.addParameters(builder, parametersOffset);
    Method.addTypeParams(builder, typeParamsOffset);
    Method.addReturnType(builder, returnTypeOffset);
    Method.addName(builder, nameOffset);
    Method.addIsDeprecated(builder, isDeprecated);
    Method.addIsStatic(builder, isStatic);
    return Method.endMethod(builder);
  }

  public static void startMethod(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addReturnType(FlatBufferBuilder builder, int returnTypeOffset) { builder.addOffset(1, returnTypeOffset, 0); }
  public static void addTypeParams(FlatBufferBuilder builder, int typeParamsOffset) { builder.addOffset(2, typeParamsOffset, 0); }
  public static int createTypeParamsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTypeParamsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addParameters(FlatBufferBuilder builder, int parametersOffset) { builder.addOffset(3, parametersOffset, 0); }
  public static int createParametersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startParametersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addIsStatic(FlatBufferBuilder builder, boolean isStatic) { builder.addBoolean(4, isStatic, false); }
  public static void addIsDeprecated(FlatBufferBuilder builder, boolean isDeprecated) { builder.addBoolean(5, isDeprecated, false); }
  public static void addDocumentation(FlatBufferBuilder builder, int documentationOffset) { builder.addOffset(6, documentationOffset, 0); }
  public static int endMethod(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Method get(int j) { return get(new Method(), j); }
    public Method get(Method obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

