// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RecipeSchemaBinding extends com.google.flatbuffers.Table {
  public static RecipeSchemaBinding getRootAsRecipeSchemaBinding(ByteBuffer _bb) { return getRootAsRecipeSchemaBinding(_bb, new RecipeSchemaBinding()); }
  public static RecipeSchemaBinding getRootAsRecipeSchemaBinding(ByteBuffer _bb, RecipeSchemaBinding obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RecipeSchemaBinding __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String namespace() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer namespaceAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer namespaceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String schemaId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer schemaIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer schemaIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String recipeClass() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipeClassAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer recipeClassInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo keys(int j) { return keys(new io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo(), j); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo keys(io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int keysLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo.Vector keysVector() { return keysVector(new io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo.Vector()); }
  public io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo.Vector keysVector(io.github.tritium_launcher.launcher.extension.kubejs.typings.RecipeKeyInfo.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String documentation() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer documentationAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer documentationInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createRecipeSchemaBinding(FlatBufferBuilder builder,
      int namespaceOffset,
      int schemaIdOffset,
      int recipeClassOffset,
      int keysOffset,
      int documentationOffset) {
    builder.startTable(5);
    RecipeSchemaBinding.addDocumentation(builder, documentationOffset);
    RecipeSchemaBinding.addKeys(builder, keysOffset);
    RecipeSchemaBinding.addRecipeClass(builder, recipeClassOffset);
    RecipeSchemaBinding.addSchemaId(builder, schemaIdOffset);
    RecipeSchemaBinding.addNamespace(builder, namespaceOffset);
    return RecipeSchemaBinding.endRecipeSchemaBinding(builder);
  }

  public static void startRecipeSchemaBinding(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addNamespace(FlatBufferBuilder builder, int namespaceOffset) { builder.addOffset(0, namespaceOffset, 0); }
  public static void addSchemaId(FlatBufferBuilder builder, int schemaIdOffset) { builder.addOffset(1, schemaIdOffset, 0); }
  public static void addRecipeClass(FlatBufferBuilder builder, int recipeClassOffset) { builder.addOffset(2, recipeClassOffset, 0); }
  public static void addKeys(FlatBufferBuilder builder, int keysOffset) { builder.addOffset(3, keysOffset, 0); }
  public static int createKeysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startKeysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDocumentation(FlatBufferBuilder builder, int documentationOffset) { builder.addOffset(4, documentationOffset, 0); }
  public static int endRecipeSchemaBinding(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RecipeSchemaBinding get(int j) { return get(new RecipeSchemaBinding(), j); }
    public RecipeSchemaBinding get(RecipeSchemaBinding obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

