/*
 * Copyright (c) 2025 FooterMan and contributors.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RecipeKeyInfo extends com.google.flatbuffers.Table {
  public static RecipeKeyInfo getRootAsRecipeKeyInfo(ByteBuffer _bb) { return getRootAsRecipeKeyInfo(_bb, new RecipeKeyInfo()); }
  public static RecipeKeyInfo getRootAsRecipeKeyInfo(ByteBuffer _bb, RecipeKeyInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RecipeKeyInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String type() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer typeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public boolean optional() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createRecipeKeyInfo(FlatBufferBuilder builder,
      int nameOffset,
      int typeOffset,
      boolean optional) {
    builder.startTable(3);
    RecipeKeyInfo.addType(builder, typeOffset);
    RecipeKeyInfo.addName(builder, nameOffset);
    RecipeKeyInfo.addOptional(builder, optional);
    return RecipeKeyInfo.endRecipeKeyInfo(builder);
  }

  public static void startRecipeKeyInfo(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(1, typeOffset, 0); }
  public static void addOptional(FlatBufferBuilder builder, boolean optional) { builder.addBoolean(2, optional, false); }
  public static int endRecipeKeyInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RecipeKeyInfo get(int j) { return get(new RecipeKeyInfo(), j); }
    public RecipeKeyInfo get(RecipeKeyInfo obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

