// automatically generated by the FlatBuffers compiler, do not modify

package io.github.tritium_launcher.launcher.extension.kubejs.typings;

@SuppressWarnings("unused")
public final class TypeKind {
  private TypeKind() { }
  public static final byte Primitive = 0;
  public static final byte Class = 1;
  public static final byte Interface = 2;
  public static final byte Array = 3;
  public static final byte Event = 4;

  public static final String[] names = { "Primitive", "Class", "Interface", "Array", "Event", };

  public static String name(int e) { return names[e]; }
}

